apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - update
  - delete
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - delete
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - hdo.smartive.ch
  resources:
  - clusterdatabasehosts
  verbs:
  - get
- apiGroups:
  - hdo.smartive.ch
  resources:
  - clusterdatabasehosts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hdo.smartive.ch
  resources:
  - clusterdatabasehosts
  verbs:
  - get
- apiGroups:
  - hdo.smartive.ch
  resources:
  - clusterdatabasehosts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hdo.smartive.ch
  resources:
  - clusterdatabasehosts
  verbs:
  - get
  - watch
  - update
- apiGroups:
  - hdo.smartive.ch
  resources:
  - clusterdatabasehosts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hdo.smartive.ch
  resources:
  - danglingdatabases
  verbs:
  - '*'
- apiGroups:
  - ''
  - admissionregistration.k8s.io
  resources:
  - services
  - validatingwebhookconfigurations
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
