version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  labels:
  - dependencies
  ignore:
  - dependency-name: KubeOps
    versions:
    - 2.5.0
    - 3.0.0
    - 3.1.0
    - 4.0.0
    - 4.0.1
    - 4.0.10
    - 4.0.11
    - 4.0.13
    - 4.0.2
    - 4.0.3
    - 4.0.4
    - 4.0.5
    - 4.0.7
    - 4.0.8
    - 4.0.9
  - dependency-name: Nuke.Common
    versions:
    - 5.0.2
    - 5.1.0
