apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterdatabasehosts.hdo.smartive.ch
spec:
  group: hdo.smartive.ch
  names:
    kind: ClusterDatabaseHost
    listKind: ClusterDatabaseHostList
    plural: clusterdatabasehosts
    singular: clusterdatabasehost
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ClusterDatabaseHost is the Schema for the clusterdatabasehosts API
      properties:
        status:
          description: Status information about the cluster database.
          properties:
            connected:
              description: Determines the state if the host can be connected to.
              type: boolean
            lastConnectionTest:
              description: The timestamp of the last connection check.
              format: date-time
              nullable: true
              type: string
            error:
              description: If given, the error message for the connection attempt.
              type: string
          type: object
        spec:
          description: Configuration for a cluster database host.
          properties:
            type:
              description: Determines the type of the database host.
              type: string
            host:
              description: The hostname of the database.
              type: string
            port:
              description: Port to connect.
              format: int32
              type: integer
            secretName:
              description: The name of the secret that contains the connection information for this host.
              type: string
            secretNamespace:
              description: The namespace of the secret that contains the connection information for this host.
              type: string
            usernameKey:
              description: The name of the secret data key that contains the username for the connection.
              type: string
            passwordKey:
              description: The name of the secret data key that contains the password for the connection.
              type: string
          type: object
        metadata:
          type: object
        apiVersion:
          type: string
        kind:
          type: string
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
       type: string
          kind:
            type: string
        type: object
    served: true
    storage: true
    subresources:
      status: {}
