apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hosteddatabases.hdo.smartive.ch
spec:
  group: hdo.smartive.ch
  names:
    kind: HostedDatabase
    listKind: HostedDatabaseList
    plural: hosteddatabases
    singular: hosteddatabase
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        status:
          description: Status of the hosted database.
          properties:
            dbName:
              description: Name that is used on the host.
              nullable: true
              type: string
            dbHost:
              description: Host name of the database.
              nullable: true
              type: string
            configMapName:
              description: Name of the config map that contains the host / port / name.
              nullable: true
              type: string
            secretName:
              description: Name of the secret in the namespace that contains username / password.
              nullable: true
              type: string
            error:
              description: Any error that might occur.
              nullable: true
              type: string
          type: object
        spec:
          description: Describes the hosted database specification.
          properties:
            host:
              description: The name of the host to be used.
              type: string
          required:
          - host
          type: object
        metadata:
          type: object
        apiVersion:
          type: string
        kind:
          type: string
      type: object
  versions:
  - name: v1
    served: true
    storage: true
