apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterdatabasehosts.hdo.smartive.ch
spec:
  group: hdo.smartive.ch
  names:
    kind: ClusterDatabaseHost
    listKind: ClusterDatabaseHostList
    plural: clusterdatabasehosts
    singular: clusterdatabasehost
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Determines the state if the host can be connected to.
      jsonPath: .status.connected
      name: Connected
      priority: 0
      type: boolean
    - description: The hostname of the database.
      jsonPath: .spec.host
      name: Host
      priority: 0
      type: string
    name: v2
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status information about the cluster database.
            properties:
              connected:
                description: Determines the state if the host can be connected to.
                type: boolean
              lastConnectionCheck:
                description: The timestamp of the last connection check.
                format: date-time
                nullable: true
                type: string
              error:
                description: If given, the error message for the connection attempt.
                nullable: true
                type: string
            type: object
          spec:
            description: Configuration for a cluster database host.
            properties:
              type:
                description: Determines the type of the database host.
                enum:
                - MySql
                - Postgres
                type: string
              host:
                description: The hostname of the database.
                type: string
              port:
                description: Port to connect.
                format: int32
                type: integer
              credentialsSecret:
                description: A reference to a secret that contains a username and a password to connect to this database host.
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                type: object
              usernameKey:
                description: The name of the secret data key that contains the username for the connection (defaults to 'username').
                type: string
              passwordKey:
                description: The name of the secret data key that contains the password for the connection (defaults to 'password').
                type: string
            required:
            - type
            - host
            - port
            - credentialsSecret
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
