apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: danglingdatabases.hdo.smartive.ch
spec:
  group: hdo.smartive.ch
  names:
    kind: DanglingDatabase
    listKind: DanglingDatabaseList
    plural: danglingdatabases
    singular: danglingdatabase
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The name of the host to be used.
      jsonPath: .spec.host
      name: Host
      priority: 0
      type: string
    - description: The name of the database (on the host).
      jsonPath: .spec.name
      name: Name
      priority: 0
      type: string
    name: v2
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: Describes the dangling database specification.
            properties:
              host:
                description: The name of the host to be used.
                type: string
              name:
                description: The name of the database (on the host).
                type: string
              credentialsSecret:
                description: A reference to the secret that contains the credentials for the dangling database.
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                type: object
            required:
            - host
            - name
            - credentialsSecret
            type: object
        type: object
    served: true
    storage: true
